version: "3.9"

services:
  xaseco:
    build: xaseco
    init: true
    restart: unless-stopped
    volumes:
      - gamedata:/GameData
    ports:
      - 8002:8002
  dedicated:
    build: dedicated
    init: true
    restart: unless-stopped
    volumes:
      - gamedata:/GameData
      - ./dedicated/dedicated.xml:/GameData/Config/dedicated.xml
      - ./dedicated/game.xml:/GameData/Tracks/game.xml
    expose:
      - 2350 # server
      - 3450 # p2p
      - 5000 # XMLRPC only local comms
    ports:
      - 2350:2350/tcp
      - 2350:2350/udp
      - 3450:3450/tcp
      - 3450:3450/udp
  db:
    image: mysql:5
    restart: unless-stopped
    env_file: ./db/.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  gamedata:
    external: true
