services:
  xaseco:
    build: xaseco
    init: true
    restart: unless-stopped
    volumes:
      - ../dynmaps:/GameData/Tracks/Challenges/dynmaps
      - gamedata:/GameData
    ports:
      - 8002:8002
  dedicated:
    build: dedicated
    init: true
    restart: unless-stopped
    volumes:
      - ../dynmaps:/GameData/Tracks/Challenges/dynmaps
      - gamedata:/GameData
      - ./dedicated/dedicated.xml:/GameData/Config/dedicated.xml
    expose:
      - 2350 # server
      - 3450 # p2p
    ports:
      - 2350:2350/tcp
      - 2350:2350/udp
      - 3450:3450/tcp
      - 3450:3450/udp
  db:
    image: mysql:5
    restart: unless-stopped
    env_file: ./db/env
    ulimits:
        nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
            soft: 1048576
            hard: 1048576
    
    mem_limit: 1G
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  gamedata:
    external: true
