version: "3.9"

services:
  xaseco:
    build: xaseco
    init: true
    restart: unless-stopped
    volumes:
      - ./xaseco/adminops.xml:/adminops.xml
      - ./xaseco/config.xml:/config.xml
      - ./xaseco/localdatabase.xml:/localdatabase.xml
      - ./xaseco/dedimania.xml:/dedimania.xml
      - ./xaseco/plugins.xml:/plugins.xml
      - ./xaseco/bestcps.xml:/bestcps.xml
      - ./xaseco/fufi_menu_config.xml:/fufi_menu_config.xml
      - ./xaseco/records_eyepiece.xml:/records_eyepiece.xml
      - ./xaseco/spyke_allcps.xml:/spyke_allcps.xml
    ports:
      - 8002:8002
  dedicated:
    build: dedicated
    init: true
    restart: unless-stopped
    volumes:
      - ./dedicated/Config:/GameData/Config
      - ./dedicated/game.xml:/GameData/Tracks/game.xml
      - ./dedicated/Challenges:/GameData/Tracks/Challenges
    expose:
      - 2350 # server
      - 3450 # p2p
      - 5000 # XMLRPC only local comms
    ports:
      - 2350:2350/tcp
      - 2350:2350/udp
      - 3450:3450/tcp
      - 3450:3450/udp
  db:
    image: mysql:5
    restart: unless-stopped
    env_file: ./db/.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

