version: "3.9"

services:
  dedicated:
    build: dedicated
    init: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./dedicated/Config
        target: /GameData/Config
      - type: bind
        source: ./dedicated/game.xml
        target: /GameData/Tracks/game.xml
      - type: bind
        source: ./dedicated/Challenges
        target: /GameData/Tracks/Challenges
    expose:
      - 2350 # server
      - 3450 # p2p
      - 5000 # XMLRPC only local comms
    ports:
      - 2350:2350
      - 3450:3450
